#!/usr/bin/env bash

# ==============================================================================
# Dynamic Ray Serve Deployment Script (serve_vision_tool.sh) - Final Corrected Version
#
# Purpose:
# 1. Bypasses `working_dir` validation by directly setting PYTHONPATH via `env_vars`.
#    This assumes the code exists at the same path on all cluster nodes.
# 2. Automatically detects cluster CPUs and calculates replica count.
# 3. Generates the final, correct temporary YAML configuration file.
# 4. Deploys the application.
# ==============================================================================

set -e
set -o pipefail

# --- Dynamic Path Resolution ---
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
export BASE_DIR=${BASE_DIR:-"your-code-dir"}
echo "✅ Project root detected: ${BASE_DIR}"

# --- Configurable Variables ---
APP_IMPORT_PATH="recipe.med.serve_ray:vision_app"
TIMESTAMP=$(date +"%m%d-%H-%M-%S")
RANDOM_NUM=$(shuf -i 0-99999 -n 1)
CONFIG_FILE="${SCRIPT_DIR}/serve_ray_${TIMESTAMP}_${RANDOM_NUM}.yaml"

# --- Script Body ---
echo "🚀 Starting the dynamic Ray Serve deployment script..."

# 1. Check Ray cluster connection
echo "Checking Ray cluster connection..."
if ! ray health-check > /dev/null; then
    echo "❌ Error: Could not connect to the Ray cluster."
    exit 1
fi
echo "✅ Successfully connected to the Ray cluster."

# 2. Get total CPU cores
echo "🔎 Fetching cluster resources..."
TOTAL_CPUS_FLOAT=$(ray status | awk '/CPU/ {split($1, a, "/"); print a[2]}')

if [ -z "$TOTAL_CPUS_FLOAT" ]; then
    echo "❌ Error: Failed to parse total CPUs from 'ray status' command."
    exit 1
fi
TOTAL_CPUS=$(printf "%.0f" "$TOTAL_CPUS_FLOAT")
echo "✅ Detected a total of ${TOTAL_CPUS} CPU cores in the cluster."

# RESERVED_CPUS=36

# 3. Calculate the number of replicas
echo "🧮 Calculating the number of application replicas (num_replicas)..."
# NUM_REPLICAS=$((TOTAL_CPUS - RESERVED_CPUS))
#
NUM_REPLICAS=8

if [ "$NUM_REPLICAS" -lt 1 ]; then
    NUM_REPLICAS=1
fi
echo "✅ Final number of replicas to deploy: ${NUM_REPLICAS}."

# 4. Generate the deployment YAML using `env_vars`
echo "📄 Generating deployment configuration file: ${CONFIG_FILE}..."
cat > "$CONFIG_FILE" << EOF
# This file is auto-generated by the serve_vision_tool.sh script
applications:
  - name: vision_app
    import_path: ${APP_IMPORT_PATH}
    runtime_env:
      env_vars:
        # THE FINAL FIX: Directly set PYTHONPATH for the workers.
        PYTHONPATH: "${BASE_DIR}"
    deployments:
      - name: VisionToolServer
        num_replicas: ${NUM_REPLICAS}
        ray_actor_options:
          num_cpus: 1
          num_gpus: 0
EOF

echo "✅ Configuration file generated successfully using env_vars."

# 5. Deploy the application
echo "🚀 Deploying the application..."
# The `cd` command is no longer necessary with this approach.
serve deploy "${CONFIG_FILE}"

if [ $? -eq 0 ]; then
    echo "🎉 Deployment/update successful!"
else
    echo "❌ Deployment failed. Please check the logs above."
    if [ -f "${CONFIG_FILE}" ]; then
        rm -f "${CONFIG_FILE}"
    fi
    exit 1
fi

# 6. Clean up the temporary file
echo "🧹 Cleaning up temporary configuration file..."
if [ -f "${CONFIG_FILE}" ]; then
    rm "${CONFIG_FILE}"
    echo "✅ Cleanup complete."
else
    echo "⚠️ Configuration file not found, skipping cleanup."
fi
echo "✨ Script execution finished!"

source "${SCRIPT_DIR}/get_head_node_ip.sh"
